name: Build

on:
  pull_request: {}
  push: { branches: [master] }
jobs:
  build:
    name: ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unity: ["2023.1.12f1"] 
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get package version
        id: version
        run: |
          version=$(jq -r '.version' ./package.json)
          echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV
          echo "Package version: $version"

      - name: Create minimal Unity project
        run: |
          TMP_PATH=$(mktemp -d)
          echo "Creating temp Unity project at $TMP_PATH"
          mkdir -p $TMP_PATH/Assets
          mkdir -p $TMP_PATH/Packages
          mkdir -p $TMP_PATH/ProjectSettings
          echo '{
            "dependencies": {
                "com.alexeytaranov.serializereferencedropdown": "file:../"
              }
            }' > $TMP_PATH/Packages/manifest.json
          echo "m_EditorVersion: ${{ matrix.unity }}" > $TMP_PATH/ProjectSettings/ProjectVersion.txt

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: BuildProject/Library
          key: Library-${{ matrix.unity }}-${{ matrix.targetPlatform }}

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unity }}
          projectPath: ${{ env.TMP_PROJECT_PATH }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: "SerialReferenceDropdownDemo-${{ env.PACKAGE_VERSION }}"
          buildPath: build/${{ matrix.targetPlatform }}/${{ env.PACKAGE_VERSION }}        
