name: Build

on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  build:
    name: ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unity: ["2023.1.12f1"]
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
          - iOS
          - Android
          - WebGL

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get package version
        id: version
        run: |
          version=$(jq -r '.version' ./package.json)
          echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV
          echo "Package version: $version"

      - name: Create minimal Unity project
        run: |
          TMP_PATH=$(mktemp -d)
          echo "Creating temp Unity project at $TMP_PATH"
          mkdir -p $TMP_PATH/Assets
          mkdir -p $TMP_PATH/Packages
          mkdir -p $TMP_PATH/ProjectSettings
          echo '{
            "dependencies": {
              "com.alexeytaranov.serializereferencedropdown": "file:../"
            }
          }' > $TMP_PATH/Packages/manifest.json
          echo "m_EditorVersion: ${{ matrix.unity }}" > $TMP_PATH/ProjectSettings/ProjectVersion.txt
          echo "TMP_PROJECT_PATH=$TMP_PATH" >> $GITHUB_ENV

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: ${{ env.TMP_PROJECT_PATH }}/Library
          key: Library-${{ matrix.unity }}-${{ matrix.targetPlatform }}

      # üîπ –í–∞–∂–Ω–æ ‚Äî –∞–∫—Ç–∏–≤–∞—Ü–∏—è Unity –ø–µ—Ä–µ–¥ –±–∏–ª–¥–æ–º
      - name: Activate Unity
        uses: game-ci/unity-activate@v3
        with:
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: ${{ matrix.unity }}
          projectPath: ${{ env.TMP_PROJECT_PATH }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: "SerialReferenceDropdownDemo-${{ env.PACKAGE_VERSION }}"
          buildPath: build/${{ matrix.targetPlatform }}/${{ env.PACKAGE_VERSION }}
